### ISSUE TITLE
af() breaks when the model has all continuous variables

### ISSUE THREAD

**Issue by mdozmorov** [garthtarr/mplot#1]
Fit is a simple lm object. Made with numeric variables from a data frame. af() with default parameters breaks with:

Error in UseMethod("droplevels") : 
  no applicable method for 'droplevels' applied to an object of class "character"

**Comment by garthtarr** [comment]
Could you give a minimum working example of the failure?

This works for me with all numeric variables:

```s
n = 100
set.seed(11)
e = rnorm(n)
x1 = rnorm(n)
x2 = rnorm(n)
x3 = x1^2
x4 = x2^2
x5 = x1*x2
y = 1 + x1 + x2 + e
dat = data.frame(y,x1,x2,x3,x4,x5)
lm1 = lm(y~.,data=dat)
af1 = af(lm1)
```

**Comment by mdozmorov** [comment]
Thanks, Garth, the example works. Attaching the one that breaks:
[mtx.txt](https://github.com/garthtarr/mplot/files/691113/mtx.txt)
mtx <- read.csv("mtx.txt", row.names = 1)
fit <- lm(y ~ ., data = mtx)
af.art <- af(fit, B = 10, cores = 3)
Error in UseMethod("droplevels") : 
  no applicable method for 'droplevels' applied to an object of class "character"

**Comment by garthtarr** [comment]
Your example still worked OK on my machine, but I've updated the line where I use `droplevels` in the `af()` function to explicitly coerce the argument to a factor before applying `droplevels`.  Try this now and let me know if that fixes things on your end.

```
devtools::install_github("garthtarr/mplot")
require(mplot)
mtx <- read.csv("mtx.txt", row.names = 1)
fit <- lm(y ~ ., data = mtx)
af.art <- af(fit, B = 10, cores = 3)
plot(af.art)
```

**Comment by mdozmorov** [comment]
Apparently, some package incompatibilities. The example works now, thanks!
